export const ADD_POINT = "ADD_POINT";
export const ADD_HIGHLIGHTING_OF_POINT = "ADD_HIGHLIGHTING_OF_POINT";
export const REMOVE_HIGHLIGHTING_OF_POINT = "REMOVE_HIGHLIGHTING_OF_POINT";
export const REMOVE_POINT = "REMOVE_POINT";
export const REMOVE_ALL_POINTS = "REMOVE_ALL_POINTS";